-- Day 04: Aggregate Functions & GROUP BY - Setup Script
-- Run this in pgAdmin to create today's tables

DROP TABLE IF EXISTS sales_transactions;

CREATE TABLE sales_transactions (
    transaction_id  SERIAL PRIMARY KEY,
    sales_rep       VARCHAR(100)   NOT NULL,
    department      VARCHAR(50)    NOT NULL,
    client_name     VARCHAR(100)   NOT NULL,
    product_tier    VARCHAR(20)    NOT NULL,
    deal_amount     NUMERIC(10, 2) NOT NULL,
    transaction_date DATE          NOT NULL,
    region          VARCHAR(50)    NOT NULL,
    is_renewal      BOOLEAN        NOT NULL DEFAULT FALSE
);

INSERT INTO sales_transactions (sales_rep, department, client_name, product_tier, deal_amount, transaction_date, region, is_renewal)
VALUES
    ('Amara Osei',      'Enterprise',    'Vertex Solutions',       'Enterprise',    52340.00, '2025-01-07', 'London',         FALSE),
    ('Amara Osei',      'Enterprise',    'Quantum Analytics',      'Business',      18750.50, '2025-01-14', 'London',         TRUE),
    ('Amara Osei',      'Enterprise',    'Atlas Digital',          'Enterprise',    67200.00, '2025-02-03', 'South East',     FALSE),
    ('Amara Osei',      'Enterprise',    'Pinnacle Tech',          'Business',      12800.00, '2025-03-18', 'London',         TRUE),
    ('Amara Osei',      'Enterprise',    'Orion Systems',          'Professional',   7450.00, '2025-04-22', 'South East',     FALSE),
    ('Ravi Kapoor',     'Mid-Market',    'Birch & Partners',       'Professional',   5200.00, '2025-01-10', 'North West',     FALSE),
    ('Ravi Kapoor',     'Mid-Market',    'Clearview Data',         'Business',      11340.75, '2025-01-28', 'Scotland',       TRUE),
    ('Ravi Kapoor',     'Mid-Market',    'Forge Analytics',        'Professional',   3890.00, '2025-02-15', 'North West',     FALSE),
    ('Ravi Kapoor',     'Mid-Market',    'Summit Labs',            'Starter',        1250.00, '2025-03-05', 'Scotland',       FALSE),
    ('Ravi Kapoor',     'Mid-Market',    'Nimbus Cloud',           'Business',      15600.00, '2025-04-12', 'North West',     TRUE),
    ('Sienna Clarke',   'SMB',           'Little Oak Studio',      'Starter',         890.00, '2025-01-15', 'Wales',          FALSE),
    ('Sienna Clarke',   'SMB',           'Fern & Ivy Co',         'Starter',        1450.00, '2025-02-01', 'Wales',          FALSE),
    ('Sienna Clarke',   'SMB',           'Coastal Creative',       'Professional',   4200.00, '2025-02-20', 'South East',     TRUE),
    ('Sienna Clarke',   'SMB',           'Pixel & Grain',         'Starter',        2100.00, '2025-03-14', 'West Midlands',  FALSE),
    ('Sienna Clarke',   'SMB',           'River Digital',          'Professional',   6780.00, '2025-04-30', 'Wales',          TRUE),
    ('Finn McCarthy',   'Partnerships',  'TechBridge UK',          'Business',      22000.00, '2025-01-20', 'East Midlands',  FALSE),
    ('Finn McCarthy',   'Partnerships',  'Innovate Alliance',      'Enterprise',    45800.00, '2025-02-10', 'London',         FALSE),
    ('Finn McCarthy',   'Partnerships',  'DataFlow Partners',      'Business',      19500.00, '2025-03-01', 'North East',     TRUE),
    ('Finn McCarthy',   'Partnerships',  'Catalyst Group',         'Enterprise',    58900.00, '2025-04-08', 'London',         FALSE),
    ('Finn McCarthy',   'Partnerships',  'NexGen Solutions',       'Professional',   7100.00, '2025-05-15', 'East Midlands',  TRUE),
    ('Yuki Tanaka',     'Enterprise',    'Helix Corp',             'Enterprise',    41200.00, '2025-01-25', 'Scotland',       FALSE),
    ('Yuki Tanaka',     'Enterprise',    'Meridian Global',        'Business',      24500.00, '2025-02-18', 'London',         TRUE),
    ('Yuki Tanaka',     'Enterprise',    'Apex Industries',        'Enterprise',    63000.00, '2025-03-10', 'South East',     FALSE),
    ('Yuki Tanaka',     'Enterprise',    'Crown Analytics',        'Professional',   5800.00, '2025-04-20', 'Scotland',       FALSE),
    ('Yuki Tanaka',     'Enterprise',    'Skyline Digital',        'Business',      16300.00, '2025-05-28', 'London',         TRUE),
    ('Kwame Mensah',    'Mid-Market',    'Bolt Media',             'Professional',   4100.00, '2025-01-30', 'West Midlands',  FALSE),
    ('Kwame Mensah',    'Mid-Market',    'Prism Analytics',        'Business',       9800.00, '2025-02-22', 'North East',     FALSE),
    ('Kwame Mensah',    'Mid-Market',    'Echo Ventures',          'Starter',        1800.00, '2025-03-15', 'West Midlands',  TRUE),
    ('Kwame Mensah',    'Mid-Market',    'Crest Solutions',        'Professional',   6200.00, '2025-04-25', 'North East',     FALSE),
    ('Kwame Mensah',    'Mid-Market',    'Horizon Labs',           'Business',      13400.00, '2025-05-30', 'West Midlands',  TRUE),
    ('Isla Nguyen',     'SMB',           'Amber & Co',             'Starter',        1100.00, '2025-01-12', 'East Midlands',  FALSE),
    ('Isla Nguyen',     'SMB',           'Jade Digital',           'Professional',   3500.00, '2025-02-05', 'North West',     FALSE),
    ('Isla Nguyen',     'SMB',           'Willow Creative',        'Starter',         750.00, '2025-03-20', 'East Midlands',  TRUE),
    ('Isla Nguyen',     'SMB',           'Maple Analytics',        'Professional',   5900.00, '2025-04-15', 'North West',     FALSE),
    ('Isla Nguyen',     'SMB',           'Cedar Tech',             'Business',       8500.00, '2025-05-22', 'East Midlands',  TRUE),
    ('Mateo Silva',     'Partnerships',  'LinkBridge Co',          'Business',      20100.00, '2025-01-18', 'London',         FALSE),
    ('Mateo Silva',     'Partnerships',  'Unity Partners',         'Enterprise',    35600.00, '2025-02-25', 'South East',     TRUE),
    ('Mateo Silva',     'Partnerships',  'Synergy Group',          'Professional',   6400.00, '2025-03-28', 'London',         FALSE),
    ('Mateo Silva',     'Partnerships',  'Pathway Digital',        'Business',      17800.00, '2025-04-18', 'South East',     FALSE),
    ('Mateo Silva',     'Partnerships',  'Alliance Tech',          'Enterprise',    48200.00, '2025-05-10', 'London',         TRUE),
    ('Leila Hussain',   'Enterprise',    'Zenith Corp',            'Enterprise',    55400.00, '2025-02-08', 'North West',     FALSE),
    ('Leila Hussain',   'Enterprise',    'Vanguard Analytics',     'Business',      21700.00, '2025-03-12', 'London',         TRUE),
    ('Leila Hussain',   'Enterprise',    'Frontier Systems',       'Enterprise',    70100.00, '2025-04-02', 'North West',     FALSE),
    ('Leila Hussain',   'Enterprise',    'Titan Digital',          'Professional',   4600.00, '2025-05-05', 'London',         FALSE),
    ('Leila Hussain',   'Enterprise',    'Summit Analytics',       'Business',      19200.00, '2025-06-18', 'North West',     TRUE),
    ('Euan Campbell',   'SMB',           'Glen Tech',              'Starter',        1600.00, '2025-01-22', 'Scotland',       FALSE),
    ('Euan Campbell',   'SMB',           'Thistle Digital',        'Professional',   3200.00, '2025-02-14', 'Scotland',       TRUE),
    ('Euan Campbell',   'SMB',           'Loch Analytics',         'Starter',        2400.00, '2025-03-25', 'Scotland',       FALSE),
    ('Euan Campbell',   'SMB',           'Highland Solutions',     'Business',      10500.00, '2025-04-28', 'Scotland',       FALSE),
    ('Euan Campbell',   'SMB',           'Cairn Media',            'Professional',   5100.00, '2025-06-02', 'Scotland',       TRUE);
